config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :product, :style, :material, :item_code, :stock, presence: true

  def day
    self.created_at.strftime("%Y/%m/%d")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
    #@entries = Entry.where("created_at >= ?", Date.today)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:product, :style, :material, :item_code, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <% @entries.each do |day, entries| %>
      <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered"><%= day %> に変動した製品</h3>

      <% entries.each do |entry| %>
        <%= link_to entry_path(entry) do %>
          <div class="card">
            <div class="card-content">
              <strong><%= entry.product %></strong><br/>
              タイプ：<%= entry.style %>,
              生地：<%= entry.material %>,
              製品コード：<%= entry.item_code %>,
              在庫数：<%= entry.stock %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class="message-body">
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product, class: "label" %>
    <%= form.text_field :product, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :style, class: "label" %>
    <%= form.text_field :style, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :material, class: "label" %>
    <%= form.text_field :material, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :item_code, class: "label" %>
    <%= form.text_field :item_code, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :stock, class: "label" %>
    <%= form.number_field :stock, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h4 class="is-size-2 has-text-weight-bold mb-3 has-text-centered">変更</h4>
      <%= render 'form', entry: @entry %>
      <%= link_to 'Back', entries_path %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Inventory &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.product %></p>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class="has-text-weight-bold">タイプ：<%= entry.style %></span></p>
            <p><span class="has-text-weight-bold">生地：<%= entry.material %></span></p>
            <p><span class="has-text-weight-bold">製品コード：<%= entry.item_code %></span></p>
            <p><span class="has-text-weight-bold">在庫数：<%= entry.stock %></span></p>
            <p class="italic">登録：<%= time_ago_in_words(entry.created_at) %> 前</p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to '表示', entry, class: "card-footer-item" %>
          <%= link_to '変更', edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to '削除', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to "変動を確認する", archives_index_path, class: "button is-link is-outlined is-centered" %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h4 class="is-size-2 has-text-weight-bold mb-3">新規作成</h4>
      <%= render 'form', entry: @entry %>
      <%= link_to 'Back', entries_path %>
  </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.product %>
  <%= @entry.item_code %>
  <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading">
        <%= @entry.product %>
      </p>
      <div class="panel-block">
        タイプ：<%= @entry.style %>
      </div>
      <div class="panel-block">
        生地：<%= @entry.material %>
      </div>
      <div class="panel-block">
        製品コード：<%= @entry.item_code %>
      </div>
      <div class="panel-block">
        在庫数：<%= @entry.stock %>
      </div> 
    </nav>
    <div class="colomn is-mobile">
      <div class="colomn">
        <%= link_to "変更", edit_entry_path(@entry), class: "button is-gray" %>
        <%= link_to "削除", entries_path(@entry), method: :delete, data: { confirm: "本当に消去しますか？"}, class: "button is-gray" %>
      </div>
      <div class="column">
        <!-- -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <% if notice.present? %>
      <div class="notification is-link is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <%# app/assets/images/kasurira_logo.jpg %>
            <%= image_tag "kasurira_logo.jpg", alt: "Kasurira logo" %>
          <% end %>

        </div>
        <div class="navbar-end">
          <%= link_to "新規登録", new_entry_path, class: "button is-success" %>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          Inventory
        <% end %>
      </h1>
    </div>
  </div>
</section>